# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-06 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='max_level',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='adventure',
            name='max_party_size',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='adventure',
            name='min_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='adventure',
            name='min_party_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='adventure',
            name='system',
            field=models.CharField(choices=[('ADD1E', 'AD&D (1st edition)'), ('ADD2E', 'AD&D (2nd edition)'), ('DD3E', 'D&D (3rd edition)'), ('DD4E', 'D&D (4th edition)'), ('DD5E', 'D&D (5th edition)'), ('DDMV', 'Moldvay D&D'), ('DDMZ', 'Mentzer D&D')], default='DD5E', max_length=2),
        ),
    ]
