# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-06 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0004_auto_20170706_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventure',
            name='ratings',
        ),
        migrations.AddField(
            model_name='rating',
            name='adventure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lookup.Adventure'),
        ),
    ]
