# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-06 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0005_auto_20170706_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='page_count',
            field=models.IntegerField(default=25),
        ),
    ]
