# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-06 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0007_adventure_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
