# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-06 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0008_auto_20170706_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='min_party_size',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='system',
            field=models.CharField(choices=[('FOREST', 'Forest'), ('SWAMP', 'Swamp'), ('DUNGEON', 'Dungeon'), ('UNDERDARK', 'Underdark')], default='Dungeon', max_length=100),
        ),
    ]
