# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-06 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0009_auto_20170706_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='terrain',
            field=models.CharField(choices=[('FOREST', 'Forest'), ('SWAMP', 'Swamp'), ('DUNGEON', 'Dungeon'), ('UNDERDARK', 'Underdark')], default='Dungeon', max_length=100),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='system',
            field=models.CharField(choices=[('ADD1E', 'AD&D (1st edition)'), ('ADD2E', 'AD&D (2nd edition)'), ('DD3E', 'D&D (3rd edition)'), ('DD4E', 'D&D (4th edition)'), ('DD5E', 'D&D (5th edition)'), ('DDMV', 'Moldvay D&D'), ('DDMZ', 'Mentzer D&D')], default='DD5E', max_length=100),
        ),
    ]
