# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-06 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0010_auto_20170706_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='adv_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adventure',
            name='adv_format',
            field=models.CharField(choices=[('PRINT', 'Print'), ('PDF', 'PDF')], default='PDF', max_length=100),
        ),
    ]
