# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0013_auto_20170707_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventure',
            name='system',
        ),
        migrations.AddField(
            model_name='adventure',
            name='system',
            field=models.ManyToManyField(to='lookup.System'),
        ),
    ]
