# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0014_auto_20170707_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventure',
            name='system',
        ),
        migrations.AddField(
            model_name='adventure',
            name='system',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lookup.System'),
        ),
    ]
