# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0015_auto_20170707_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terrain_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='adventure',
            name='adv_format',
        ),
        migrations.AlterField(
            model_name='adventure',
            name='terrain',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lookup.Terrain'),
        ),
        migrations.AddField(
            model_name='adventure',
            name='adv_availability',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lookup.Availability'),
        ),
    ]
