# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-09 10:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0016_auto_20170707_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='adv_desc',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='adv_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 9, 10, 55, 52, 101888, tzinfo=utc), verbose_name='date published'),
        ),
    ]
