# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-09 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0019_auto_20170709_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='source',
            field=models.CharField(default='', max_length=200),
        ),
    ]
