# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-09 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0020_auto_20170709_0658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adventure',
            options={'permissions': (('can_add_adventure', 'Add adventure'),)},
        ),
    ]
