# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-09 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0023_auto_20170709_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adventure',
            options={'permissions': (('can_add_adventure', 'Add adventure'), ('can_edit_all_adventures', 'Edit all adventures'), ('can_edit_own_adventure', 'Edit own adventures'))},
        ),
    ]
