# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-09 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0024_auto_20170709_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventure',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='submitted_by',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
