# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-09 18:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lookup', '0025_auto_20170709_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='submitted_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
